name: Post Qiita URL to X

on:
  workflow_run:
    workflows: ["Publish Article to Qiita"]  # Qiita投稿ワークフローの名称に合わせてください
    types:
      - completed

jobs:
  post_to_x:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: 発行済み URL アーティファクトのダウンロード
      - name: Download Published URL Artifact
        uses: actions/download-artifact@v4
        with:
          name: published-url
          path: published

      # Step 2: 発行済みタイトル アーティファクトのダウンロード
      - name: Download Published Title Artifact
        uses: actions/download-artifact@v4
        with:
          name: published-title
          path: published_title

      # Step 3: アーティファクトから投稿済みの URL を読み取る
      - name: Read Published URL
        id: read_url
        run: |
          published_url=$(cat published/published_url.txt)
          echo "Published URL is: $published_url"
          echo "published_url=$published_url" >> $GITHUB_OUTPUT

      # Step 4: アーティファクトから投稿済みのタイトルを読み取る
      - name: Read Published Title
        id: read_title
        run: |
          title=$(cat published_title/published_title.txt)
          echo "Extracted title: $title"
          echo "title=$title" >> $GITHUB_OUTPUT

      # Step 5: 抽出したタイトルと投稿済み URL、ハッシュタグを含むツイート文を作成し、X API（Twitter API v2）を利用して投稿する
      - name: Post to X (Twitter API v2)
        env:
          X_API_BEARER_TOKEN: ${{ secrets.X_API_BEARER_TOKEN }}
          PUBLISHED_URL: ${{ steps.read_url.outputs.published_url }}
          TITLE: ${{ steps.read_title.outputs.title }}
        run: |
          tweet_text="${TITLE}
            ${PUBLISHED_URL}
            #Qiita
            #未経験エンジニア
            #駆け出しエンジニア"
          echo "Tweet text:"
          echo "$tweet_text"
          curl -X POST "https://api.twitter.com/2/tweets" \
            -H "Authorization: Bearer $X_API_BEARER_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"${tweet_text}\"}"
