name: Publish Article to Qiita

on:
  schedule:
    - cron: '10 8 5 2 *'  # 毎年2月5日 UTC 08:10 に実行（Boise MST 01:10 に相当）
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # ① qiita-content リポジトリ（メイン）をチェックアウト
      - name: Checkout qiita-content repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}  # push 権限が必要な場合は PAT を利用
          path: qiita-content

      # ② refuge_qiita リポジトリをチェックアウト（プライベートの場合、PAT を利用）
      - name: Checkout refuge_qiita repository
        uses: actions/checkout@v3
        with:
          repository: Taira0222/refuge_qiita
          token: ${{ secrets.MY_PAT }}
          ref: main
          path: refuge_qiita

      # ③ Node.js のセットアップ（npm 環境の安定化のため）
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # ④ Ruby のセットアップ（必要な Ruby バージョンに合わせて）
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'

      # ⑤ Qiita cli のインストール
      - name: Install qiita-cli
        run: npm install -g @qiita/qiita-cli@v1.6.1
        shell: bash

      # ⑥ Git のユーザー情報を設定（コミット用）
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # ⑦ 投稿処理スクリプトの実行
      - name: Run Publish Article Script
        run: |
          ruby <<'EOF'
          #!/usr/bin/env ruby
          require 'time'
          require 'fileutils'
          
          # ※テスト用：対象期間を2025/02/05 のみに設定
          boise_time = Time.now.getutc - (7 * 3600)
          start_date = Time.parse("2025-02-05 00:00:00")
          end_date   = Time.parse("2025-02-05 23:59:59")
          unless boise_time >= start_date && boise_time <= end_date
            puts "現在の Boise 時刻 (#{boise_time}) は実行期間外です。終了します。"
            exit 0
          end
          
          # ワークスペース上の各ディレクトリのパスを設定
          qiita_github_dir = File.join(Dir.pwd, 'qiita-content')
          public_dir       = File.join(qiita_github_dir, 'public')
          refuge_dir       = File.join(Dir.pwd, 'refuge_qiita')
          
          # Step 1: refuge_qiitaから最小番号の stock*.md ファイルを選択する
          stock_files = Dir.entries(refuge_dir).select { |f| f =~ /^stock(\d+)\.md$/ }
          if stock_files.empty?
            puts "refuge_qiita 内に対象ファイルが見つかりません。"
            exit 1
          end
          smallest_file = stock_files.sort_by { |f| f.match(/^stock(\d+)\.md$/)[1].to_i }.first
          puts "Moving file: #{smallest_file}"
          source_path = File.join(refuge_dir, smallest_file)
          dest_path   = File.join(public_dir, smallest_file)
          FileUtils.mv(source_path, dest_path)
          
          # Step 5: refuge_qiita 側で、stock ファイルの削除内容をコミット＆push
          Dir.chdir(refuge_dir) do
            puts "Committing deletion of #{smallest_file} in refuge_qiita"
            system("git add -A")
            commit_msg = "Remove #{smallest_file} after moving to qiita-content/public"
            system("git commit -m \"#{commit_msg}\"")
            system("git push")
          end
          
          # Step 2: qiita-content/public 内の article*.md ファイルから最大番号を取得し、新しい記事番号を決定する
          article_files = Dir.entries(public_dir).select { |f| f =~ /^article(\d+)\.md$/ }
          if article_files.empty?
            puts "qiita-content/public 内に article ファイルが見つかりません。"
            exit 1
          end
          max_article_num = article_files.map { |f| f.match(/^article(\d+)\.md$/)[1].to_i }.max
          new_article_num = max_article_num + 1
          new_file_name   = "article#{new_article_num}.md"
          new_file_path   = File.join(public_dir, new_file_name)
          puts "Renaming moved file to: #{new_file_name}"
          FileUtils.mv(dest_path, new_file_path)
          
          # Step 3: 新しい記事ファイルからタイトルを抽出する
          begin
            article_content = File.read(new_file_path)
            title_line = article_content.lines.find { |line| line.strip.start_with?("title:") }
            if title_line.nil?
              puts "No title found in #{new_file_name}"
              title = ""
            else
              title = title_line.sub(/^title:\s*/, "").strip
            end
            puts "Extracted title: #{title}"
            # タイトルを qiita-content 内に保存
            File.write(File.join(qiita_github_dir, "published_title.txt"), title)
          rescue => e
            puts "Error extracting title: #{e}"
            title = ""
          end
          
          # Step 4: Qiita cli を使用して記事を投稿する
          Dir.chdir(qiita_github_dir) do
            publish_cmd = "npx qiita publish article#{new_article_num}"
            puts "Running command: #{publish_cmd}"
            published_url = `#{publish_cmd}`.strip
            puts "Published URL: #{published_url}"
            # 生成された URL をファイルに保存（後続で利用）
            File.write("published_url.txt", published_url)
            
            puts "Running command: git add -A"
            system("git add -A")
            commit_msg = "Add article#{new_article_num}"
            commit_cmd = "git commit -m \"#{commit_msg}\""
            puts "Running command: #{commit_cmd}"
            system(commit_cmd)
            puts "Running command: git push"
            system("git push")
          end
          EOF
        shell: bash

      # Step 6: 投稿済み URL アーティファクトのアップロード
      - name: Upload Published URL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-url
          path: qiita-content/published_url.txt

      # Step 6 (オプション): 投稿済みタイトル アーティファクトのアップロード
      - name: Upload Published Title Artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-title
          path: qiita-content/published_title.txt
